# Generated by Django 5.2.15 on 2026-06-30 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headquarters', '0002_alter_headquarter_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='headquarters.headquarter')),
                ('sub_headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='headquarters.subheadquarter')),
            ],
        ),
    ]
