# Generated by Django 5.2.15 on 2026-06-30 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubHeadQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('headquarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='headquarters.headquarter')),
            ],
        ),
    ]
