# Generated by Django 5.2.15 on 2026-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarter',
            name='city',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
